### ISSUE TITLE
[Question] Is this project dead?

### ISSUE THREAD

**Issue by sshaplygin** [codehangar/reqlpro#9]
Hi, everyone!
At now,  is this project dead?

**Comment by csndra0504** [comment]
Hey @mrfoe7 you could say that. If someone submitted a PR we would probably merge it, but we're not likely to push code at this time.

**Comment by sshaplygin** [comment]
@csndra0504 Thanks for answer, Cassandra! I will develop submenu to execute raw queries in reql. Because in current version it doesn't implemented:(
